### ISSUE TITLE
Wire singleton objects

### ISSUE THREAD

**Issue by alexduf** [adamw/macwire#100]
I know it sounds counter intuitive but being able to wire objects (singletons) would actually be helpful.
I'm in the middle of a migration where controllers will eventually be moving from objects to classes, but I want to be able to wire them in an injected router.

To do that I can either do :
```scala
object Healthcheck extends Controller
trait AppComponents {
  lazy val Healthcheck = Healthcheck
  lazy val router = wire[Routes]
}
```

or

```scala
class Healthcheck extends Controller
trait AppComponents {
  lazy val Healthcheck = wire[Healthcheck]
  lazy val router = wire[Routes]
}
```

would it technically be possible to have the wiring working like that?

```scala
object Healthcheck extends Controller
trait AppComponents {
  lazy val Healthcheck = wire[Healthcheck]
  lazy val router = wire[Routes]
}
```

the idea being, I don't want my change (focusing on appLoader) to impact all my controllers, but equally I don't want my future controller changes to impact my applicationLoader. So the day I move my Healthcheck away from being an object to be a class, I don't have to touch my wiring.

**Comment by adamw** [comment]
I don't think that would work as if you have an `object A`, `A` is not a type (`A.type` is). So you can't write `wire[A]`, as the type parameter needs to be, well, a type :) So you could possible make `wire[A.type]` work, but I don't think that's what you are after.

**Comment by alexduf** [comment]
thanks!
