### ISSUE TITLE
getting object construction ordering

### ISSUE THREAD

**Issue by chikei** [adamw/macwire#117]
Hi, I am wondering if it's possible to get object construction ordering ?

My use case is about closing resources in proper ordering during shutdown, the naive idea was somehow get construction ordering then close resources backward.

**Comment by adamw** [comment]
There's no way to get information about the ordering "automatically", but  maybe sth like this would work:

```
lazy val muService = { addToShutdownQueue(wire[MyService])) }

def addToShutdownQueue[T](t: T): T = { queue.add(t); t }
```

where `queue` would be some kind of a concurrent queue which you would use in the closing process.
