### ISSUE TITLE
Can not wire classes with higher-kinded type variables from extended traits

### ISSUE THREAD

**Issue by randm-ch** [adamw/macwire#126]
Hi! First of all, thanks for your work on this framework, it's really helpful :-)

I encountered a problem when using MacWire with classes that have higher-kinded type variables. Here's a code example:

```
trait ConfigModule {
  ...
}

trait DatabaseModule[M[_]] extends ConfigModule {
  implicit val A: Async[M]
  lazy val transactor: Transactor[M] = new HikariTransactor[M](persistenceConfig)
}

trait NavigationRootDbModule[M[_]] extends DatabaseModule[M] {
  lazy val rootDao: RootDAO[M] = wire[RootDAO[M]]
  lazy val rootRepository: RootRepository[M] = wire[RootRepository[M]]
}
```

Here, the compiler will throw `Cannot find a value of type: [ch.randm.data.transactor.Transactor[M]]` for `wire[RootDAO[M]]`. Replacing this last statement with `new RootDAO[M](transactor)` works fine though. I played around with this a lot to find out if I did anything wrong, but it still looks like a bug to me.

Let me know if I did anything wrong or if I can help you resolve this issue. Thank you!

**Comment by randm-ch** [comment]
@adamw Sure. You could use my personal project, located [here](https://git.randm.ch/randm/randm.ch/). Just clone it, change the MacWire code in the `ch.randm.module` object and run `sbt compile`.

**Comment by adamw** [comment]
@randm-ch sorry, I had no time to look into this yet

**Comment by randm-ch** [comment]
@adamw No problem, just wanted to know if there's anything I can help with :) I'll fork your repo and have a go at it myself tonight, but since I'm still a newbie at Scala I can't promise I'll be able to fix it.

**Comment by jimmydivvy** [comment]
Has anyone had any luck with this use-case?

I can replicate it fairly easily with a simple example.

```

class Service1[F[_]] {}

class Service2[F[_]]( service1: Service1[F] ) {}

trait Service1Module[F[_]] {
  lazy val service1 = wire[Service1[F]]
}

class AppModule[F[_]] extends Service1Module[F] {
  lazy val service2 = wire[Service2[F]]
}
```

This fails to compile with the message 
```
Error:(47, 27) Cannot find a value of type: [acme.Service1[F]]
  lazy val service2 = wire[Service2[F]]
```

**Comment by randm-ch** [comment]
@jimmydivvy Sadly not. I tried fixing it but ran out of time (and my knowledge of macros is *very* limited). I'm not using MacWire for the time being because of this issue. Would love to add it again once it's solved though.
