### ISSUE TITLE
Runtime dependency switching

### ISSUE THREAD

**Issue by DaimonPl** [adamw/macwire#131]
Hi I'd like to be able to switch implementation of certain classes during runtime - based on some "profile" switch.

For example

``
abstract class SecurityFilter

class LowSecurityFilter extends SecurityFilter

class HighSecurityFilter extends SecurityFilter
``

I'd like to be able to use `SecurityFilter` as dependency in other classes and be able to switch its implementation when running JVM for example using `security_level` parameter passed as command line argument

is there any recommended way to do it or there's no way to achieve such behaviour because of compile time nature of macwire ?

**Comment by adamw** [comment]
I would just do:

```
val securityFilter = if (config.securityLevel == "high") {
  new HighSecurityFilter(...) // or using wire[]
} else {
  new LowSecurityFilter(...)
}
```

**Comment by DaimonPl** [comment]
But both HighSecurityFilter and LowSecurityFilter can have their own dependencies, they can be defined in module so how would module definition have that config available?

**Comment by adamw** [comment]
Well then the module definition needs to be parametrized with the config - either as an abstract trait member or another layer of constructor parameters.

If the dependencies are lazy, only the ones that are indeed used will be constructed.

**Comment by adamw** [comment]
e.g.

```
trait MyModule {
  def globalConfig: Config

  lazy val myModuleConfig = new MyModuleConfig(globalConfig)
  lazy val highSecFiltDependency = new ...
  lazy val securityFilter = if (myModuleConfig.securityLevel == "high") {
    new HighSecurityFilter(highSecFiltDependency, ...) // or using wire[]
  } else {
    new LowSecurityFilter(...)
  }
}

**Comment by DaimonPl** [comment]
But in that case if I'd like to have let's say `ModuleXYZ` which imports dependencies from `MyModule` then `MyModule` would need to be `object` instead of `trait`. Furthermore `globalConfig` would need to be mutable `var` set at the beginning of app and entire dependency injection would rely on fact that this mutable variable is initialized before any lazy dependency is requested.

Do I see it right of there's some other way?

**Comment by adamw** [comment]
I don't think I understand why you would need global objects or mutable variables ...

In the main method, you can do e.g.

```
val modules = new MyModule1 with MyModule2 with ... {
  lazy val globalConfig = Config.load()
}
```

and that's it

**Comment by DaimonPl** [comment]
It definitely makes more sense now :)

thx I'll give it a try

**Comment by DaimonPl** [comment]
I think those examples are enough for this topic :)
