### ISSUE TITLE
Support wiring using anonymous function parameters

### ISSUE THREAD

**Issue by adamw** [adamw/macwire#25]
Right now parameters of the enclosing method are used. It would be great if anonymous function parameters would work as well:

````scala
  class A
  class B
  class C(a: A, b: B)

  object module {
    lazy val a = wire[A]
    // doesn't work
    lazy val cf = (b: B) => wire[C]
    // works
    def cf(b: B) = wire[C]
  }
````

**Comment by adamw** [comment]
It would be good to make the 0.8 release soon, just wanted to check if maybe this could go in as well?

**Comment by mkubala** [comment]
I realized that my solution won't cover some not-so-corner cases like wire[T] placed within If-Then-Else block. I'm going to search GitHub/BitBucket for wire[T] occurences in Scala code and write more test cases.
There still will be a lot of uncovered cases, thus it may be a good idea to release some RC first and wait for feedback, before we officially announce 0.8

**Comment by adamw** [comment]
If it works for anonymous functions and gets rid of by-name matching that's already great. We don't have to make everything work perfectly upfront.

I wouldn't bother with RCs, if something doesn't work, we can do 0.8.1 within a couple of hours ;)

**Comment by mkubala** [comment]
Please, take a look on my last WIP. If everything looks good to you, then I'll update the docs, squash 'em all and send you a PR :)

**Comment by adamw** [comment]
Looks good! Would be great to have wiring work in all those places. Though we should probably mark this feature as experimental :)
