### ISSUE TITLE
Compile error on expressing the dependencies via self-types

### ISSUE THREAD

**Issue by kamran-m** [adamw/macwire#31]
`wire[T]` fails to lookup the instance when using self-types (although it works when extending the other trait). 

For instance the code block:

```scala
class A
class B(a: A)

trait ModuleA {
  lazy val a = wire[A]
}

trait ModuleB {
  self: ModuleA =>
  lazy val b = wire[B]
}
```
gets the following compile error:
```
Cannot find a value of type: [~.A]
[error]   lazy val b = wire[B]
[error]                    ^
```

**Comment by mikedmcfarland** [comment]
I would also love to see this. It's useful if you don't want to specify the specific implementations of the other modules. 
Lame workaround thats been working for me is:
```scala
trait ModuleA {
  lazy val a = wire[A]
}

trait ModuleB {
  self: ModuleA =>
  private lazy val _a = a  //defining a value for a on ModuleB
  lazy val b = wire[B]
}

```
