### ISSUE TITLE
release for 2.11.4 ?

### ISSUE THREAD

**Issue by tyrcho** [adamw/macwire#32]
Would you please make a new release for scala 2.11.4 ? 

I would also appreciate to use the #9 feature, at the moment I had to duplicate this code in my project to use it.

Thanks !

**Comment by adamw** [comment]
Coming really soon :)

**Comment by adamw** [comment]
(including #9)

**Comment by adamw** [comment]
I guess this will become "release for 2.11.5" now :)

**Comment by adamw** [comment]
0.8.0 is 2.11.5-based. Testing welcome, it has some new features/internal changes :)

**Comment by tyrcho** [comment]
thanks, seems OK at the moment.

I just found a minor regression : the default arguments of case class are not taken into account.

I had case class HearthstoneMatch(mode: GameMode = GameMode.UNDETECTED, ... // all with default values)

and now wire[HearthstoneMatch] does not work anymore, I had to replace by new HearthstoneMatch.

**Comment by adamw** [comment]
Could you open a separate issue for that? Not sure how default parameters should be "properly" handled in fact.

**Comment by tyrcho** [comment]
OK, #37

**Comment by adamw** [comment]
thx :)
