### ISSUE TITLE
wire can't find the dependencies if it's in a scope

### ISSUE THREAD

**Issue by freewind** [adamw/macwire#40]
```scala
trait Module extends Macwire{
  lazy val projectScope: Scope = new ProjectScope()

  class A()
  class B(a: A)

  lazy val b = projectScope(new B(a))
  lazy val a = projectScope(new A())
}
```

If I don't use `wire`, there is no compilation error, but:

```scala
  lazy val b = projectScope(wire[B])
  lazy val a = projectScope(wire[A])
```

Reports compilation error:

```
Error:(90, 33) Cannot find a value of type: [Module.this.A]
  lazy val b = projectScope(wire[B])
                                ^
```

**Comment by freewind** [comment]
This is much inconvenient since I have to reorder the dependencies often when I declare a new dependency

**Comment by adamw** [comment]
That's a known limitation (not directly mentioned [in the readme](https://github.com/adamw/macwire#limitations), but the same cause) of the current Scala Macros implementation.

When using scopes, it is sometimes necessary to help the compiler and add explicit type ascriptions. These variants work:

````
  lazy val b = projectScope(wire[B])
  lazy val a: A = projectScope(wire[A])
````

````
  lazy val b = projectScope(wire[B])
  lazy val a = wire[A]
````

Maybe Scala-meta will improve things :)

**Comment by freewind** [comment]
Cool, thanks. Hope macwire gets better and better, I like it
