### ISSUE TITLE
macwire macro's generate "[warn] dead code following this construct" warnings when using the -Ywarn-dead-code compiler flag

### ISSUE THREAD

**Issue by kwark** [adamw/macwire#41]
When using macwire macro's we noticed a lot of "[warn] dead code following this construct" messages being logged when compiling

It turns out these are coming from the macwire macro.

You can easily reproduce this in the macwire-activator project by adding the following line to build.sbt: scalacOptions ++= Seq("-Ywarn-dead-code")

This results in the following output:

[info] Compiling 16 Scala sources and 1 Java source to /projects/macwire-activator/target/scala-2.11/classes...
[warn] dead code following this construct
[warn] dead code following this construct
[warn] dead code following this construct
[warn] dead code following this construct
[warn] dead code following this construct
[warn] dead code following this construct
[warn] 6 warnings found
[success] Total time: 14 s, completed 29-apr-2015 15:09:39

**Comment by adamw** [comment]
Fixed in 1.0.2, should be in central shortly
