### ISSUE TITLE
Split code needed at runtime from code only needed at compile-time

### ISSUE THREAD

**Issue by backuitist** [adamw/macwire#49]
It's not a big deal but there could be a better separation. I can see a lot of macro code that lives along with runtime code such as `Tagging`.
Splitting them into 2 artifacts would make macwire lighter at runtime.

**Comment by adamw** [comment]
I was thinking about that, but `Tagging` is just ~10 lines, and the whole project is only a handful of classes. I suspect most people add it to the default scope anyway?

**Comment by backuitist** [comment]
> I was thinking about that, but Tagging is just ~10 lines

I guess you'll need `Wired` as well.

> the whole project is only a handful of classes

But currently weights 150KB.

> I suspect most people add it to the default scope anyway?

That's what is described in the README. If you wanted a better scope, you'd need to make sure that neither `Tagging` nor `Wired` are used.

**Comment by adamw** [comment]
An additional good side here would be that you wouldn't need `scala-reflect` as a dependency (only used for compilation). So we would have two modules:

* `macwire-runtime`
* `macwire-macros` (depends on runtime)

`-macros` needs to depend on `-runtime` as it uses e.g. `Wired`.

`-runtime` would depend on `scala-reflect` using the `provided` configuration (is that right? that's not exactly how provided is defined, but I guess it would work as expected?)

**Comment by backuitist** [comment]
That's correct. You might want to check SO for a better scope: http://stackoverflow.com/questions/21515325/add-a-compile-time-only-dependency-in-sbt#answer-21516954

**Comment by adamw** [comment]
I pushed a major re-organization of the codebase. There are now three modules which should be used like this:

```
libraryDependencies += "com.softwaremill.macwire" %% "util" % "2.0.0-SNAPSHOT"
libraryDependencies += "com.softwaremill.macwire" %% "macros" % "2.0.0-SNAPSHOT" % "provided"
libraryDependencies += "com.softwaremill.macwire" %% "proxy" % "2.0.0-SNAPSHOT"
```

`util` contains tags & `Wired`. `macros` is a compile-time-only dependency with, well, the macros. `proxy` contains interceptors & scopes (which create proxies).

There's no more `Macwire` trait, instead you should `import com.softwaremill.macwire._`, and for tags `import com.softwaremill.macwire.tagging._`.

As this is breaking change, I bumped the version to `2.0.0-SNAPSHOT`, and deployed the snapshot. Would be great if you could test & let me know in case of problems.

**Comment by adamw** [comment]
@backuitist Republished with the latest changes 
@mkubala Would be great if you could take a look as well :)

Note that the README is still for 1.x

**Comment by backuitist** [comment]
Seems good to me!

**Comment by backuitist** [comment]
I'm going to re-organize test-code so that we make sure we're not using classes we're not supposed to.
Currently project `tests` depends on `util`. That's problematic as we can easily write a `macros` only test that depends in fact on `util`.
The idea is simply to move `util` dependent tests into the util tests. I'll figure something out to factorize test utils.

**Comment by adamw** [comment]
ah true, the macros are in a spearate project anyway. Sounds good :)
