### ISSUE TITLE
@Module annotation for automatic import

### ISSUE THREAD

**Issue by backuitist** [adamw/macwire#56]
I'm using the wire-from-import feature quite a lot in this manner:
```scala
class ModuleA {
   lazy val serviceA = wire[ServiceA]
   // ...
}

class ModuleB(moduleA: ModuleA) {
   import moduleA._
   
   lazy val serviceB = wire[ServiceB] // ServiceB depends on ServiceA
}

class ModuleC(moduleA: ModuleA,
              moduleB: ModuleB) {
   import moduleA._
   import moduleB._

  // and so on...
}
```

As you can see the import statement becomes a bit of a drag...
I'm suggesting the following:

```scala
@Module
class ModuleA {
   lazy val serviceA = wire[ServiceA]
   // ...
}

@Module
class ModuleB(moduleA: ModuleA) {  
   lazy val serviceB = wire[ServiceB] // ServiceB depends on ServiceA
}

@Module
class ModuleC(moduleA: ModuleA,
              moduleB: ModuleB) {
  // and so on...
}
```

By annotating a class `@Module` we make macwire a little more aggresive in its search for candidates:
it will automatically look at the members of the usual candidates, as if they were imported.
The annotation is compile-time only so that it can live within the `macro` artefact.

**Comment by adamw** [comment]
So what `@Module` would do is influence the lookup process to also look in members of the annotated parameters?

I'm not sure if `Module` is the right name here - if the functionality is as I describe, it doesn't really describe the effects of the annotation. Maybe `@Unwrap`? Or `@Import` or `@WireUsing`?

Also, I think the annotation would make sense for individual parameters as well? And for `val`/`def` members of the enclosing scope?

Finally, maybe we could mark it as an "experimental feature" and describe as such in the `README`?

**Comment by backuitist** [comment]
> So what @Module would do is influence the lookup process to also look in members of the annotated parameters?

Not the annotated parameters, the annotated type of the parameter. I think you have this in mind:
```scala
class ModuleA {
   lazy val serviceA = wire[ServiceA]
}

class ModuleB(@Module moduleA: ModuleA) {
  // moduleA._ is now accessible
}

class ModuleC(@Module moduleA: ModuleA) {
  // moduleA._ is now accessible
}
```

Whereas what I'm suggesting is to flag `ModuleA` as being a "module" type:

```scala
@Module
class ModuleA {
   lazy val serviceA = wire[ServiceA]
}

class ModuleB(moduleA: ModuleA) {
  // moduleA._ is accessible as its type (ModuleA) has the @Module annotation
}

class ModuleC(moduleA: ModuleA) {
  // moduleA._ is accessible too
}
```

You're proposal of having an `@Unwrap` or an `@Import` is interesting, but that's a different feature. Maybe we could open another issue for that?

**Comment by adamw** [comment]
But why would an `@Module` annotation (specifying the a class is a module) have the effect of importing the parameters of that class in the class's body? I wouldn't guess that from the name ;)

**Comment by backuitist** [comment]
That's macwire nomenclature (from the readme):
> Classes that should be wired should be organized in "modules"

It's quite natural to me that when a module _depends_ on another module its members become visible.

I'm working on a project with a lot of modules and I have something like that:
```scala
class RunnerModule(coreModule: CoreModule, webModule: WebModule, photoModule: PhotoModule, musicModule: MusicModule /* ... */) {
  import coreModule._
  import webModule._
  import photoModule._
  import musicModule._
 // ...
}
```

With this feature all the imports become unnecessary.

**Comment by adamw** [comment]
Yeah I understand the motivation and I think it would be good to include (as an experimental feature though - so that we have doors wide open to refine in the future), but even though this is macwire's nomenclature, reading code with an `@Module` annotation wouldn't be too meaningful on what it does.

On the other hand, e.g. `@WireUsingParameters` or sth like that immediately indicates that (a) it has something to do with the wiring process and (b) it involves the class parameters

You know, naming, the hardest thing in IT ;)

**Comment by backuitist** [comment]
I would agree with you if the annotation was placed on the attribute of the class:
```scala
class RunnerModule(@WireUsingParameters coreModule: CoreModule) { /*...*/ }
```
But here we really want to say "this class is a Module" and then being a Module it has some special behavior (in the context of Macwire). If you feel that it's not immediately meaningful what it does then a good solution is to have some documentation on the annotation - which I'll add soon :)

Basically when annotating a type you want to describe what is _is_ rather than what _behavior_ it will have.

Let's look at existing libraries that have annotations:

__JPA__:
```scala
@Entity
class Person { }
```
Altough it does not explicitely say what it does, it's much better than `@MakePersistent`.

__Spring__ has the `@Configuration` annotation, which is better than `@ProcessedBySpringContainerToGenerateBeanDefinitions`

And you have a documentation stating what it does: 
http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/Configuration.html

**Comment by adamw** [comment]
Ok, agreed, but still, from a class being an entity you kind of expect that it's persistent, on the other hand from a class being a module do you expect to get the imports?

It is, in some way, a composite module, right? I still can't find a good name ;)

**Comment by backuitist** [comment]
And from a class being a `@Configuration` what do you expect? ;)

I can't find a better name either, as you describe it in your readme, a `UserModule` is a module. You don't want this:
```scala
@CompositeModule
class UserModule {}
```

**Comment by adamw** [comment]
Well I'm not saying that `@Configuration` is the best example to follow as well ;)

My concern is that you read the code, and without reading the docs of the annotation, you have no idea why it compiles. I'll think about a good name over the weekend, who knows ;)

**Comment by backuitist** [comment]
> Well I'm not saying that @Configuration is the best example to follow as well ;)

Ok, let's look at scala (like me, you might be allergic to Spring ;)), how about case classes? If they were defined with an annotation (which is a minor syntactic difference) that would probably be:
```scala
@case class Person(name: String, age: Int)
```
Would it be possible to tell why `person.name` compiles without knowing the details of case classes?

Back to the `@Module`, it isn't more magical than getting your dependency implicitly or from a deep hierarchy:
```scala
trait A {
  lazy val a = wire[A]
}
trait A2 extends A { /* ... */ }
trait A3 extends A2 { /* ... */ }
trait A4 extends A3 {
  lazy val b = wire[B] // depends on A... but where does A come from?
}
```
In some month I think it's likely that we'll have expansion in the IDE (look at https://github.com/JetBrains/intellij-scala/commits/idea15.x). Then it'll be obvious where your dependency come from :)

**Comment by adamw** [comment]
Ok, I don't have any better ideas, so let's go with `@Module`, as an experimental feature, which leaves an option to rename in the future :)

**Comment by backuitist** [comment]
Cool :)
I'm now running into another problem: overriding module members. With composition by inheritance (mixin) one can easily override a member of a parent. So I'd suggest a similar mechanism when composing modules with `@Module` by simply giving local definitions a higher priority:

```scala
@Module
class ModuleA {
  lazy val a: A = wire[AImpl]
  lazy val b: B = wire[BImpl]
  lazy val c: C = wire[CImpl]
  lazy val d: D = wire[DImpl]
}

class CProvider {
   lazy val c: C = wire[CImplBis]
}

class E(a: A, b: B, c: C, d: D)

class App(moduleA: ModuleA, bParam: B, cProvider: CProvider) {
   import cProvider.c
   lazy val myA: A = wire[OtherAImpl]
   
   // myA, bParam and c have all priority over moduleA
   lazy val e: E = wire[E]  // translated to: new E(myA, bParam, c, moduleA.d)
}
```
So the idea is to look at local variables first, and then fallback to module import. Only then module import could become ambiguous. That is, if 2 modules provide the same type but it's been overridden locally then the local override wins and no ambiguity is found:
```scala
@Module class ModuleA1 { lazy val a: A = wire[A1] }
@Module class ModuleA2 { lazy val a: A = wire[A2] }

class B(a: A)

class  App(ma1: ModuleA1, ma2: ModuleA2) {
   lazy val a: A = wire[A3]
   lazy val b: B = wire[B] // fine, no ambiguity as we won't evaluate ma1 and ma2
}
```

**Comment by adamw** [comment]
Precedence of local members vs members from modules makes sense. However, what about inherited members?

**Comment by backuitist** [comment]
Good question! That should be ambiguous. It's a matter or priority level, local members = priority level 1, modules AND parents = priority level 2. Two different values of a matching type at equal priority level are ambiguous.
It's fairly easy to solve the ambiguity by importing/aliasing locally the value we want.

**Comment by adamw** [comment]
ok, sounds good :)
