### ISSUE TITLE
@Module annotation retention

### ISSUE THREAD

**Issue by backuitist** [adamw/macwire#59]
More thoughts following #56...

Currently the retention for the `@Module` annotation has been set to `SOURCE`, meaning that it will be discarded by the compiler. This allows us to leave the annotation in the `macros` artifact, but on the other hand makes it impossible, as a library author, to provide annotated modules.
A possible middle ground would be to have 2 annotations, one with `SOURCE` retention (living in the `macros` artifact) another with `CLASS` retention (living in the `utils` artifact, under a different package). That way, library authors can pick the later if they need to (bringing an extra dependency along the way), whereas application developers can be fine with the `SOURCE` retention.

http://docs.oracle.com/javase/7/docs/api/java/lang/annotation/RetentionPolicy.html

**Comment by adamw** [comment]
I still think `@Module` might be confusing, let alone if there are two annotations. Let's keep `SOURCE` for now, and if there's a need to have the annotation retained in the future, we can always move it to `util`. Right now there's no use for `@Module` other than at compile time of the sources (the annotation isn't useful in libraries anyway).
