### ISSUE TITLE
Remove wiring implicit parameters from non-implicit values

### ISSUE THREAD

**Issue by backuitist** [adamw/macwire#66]
This is making macwire more complex for, IMO, a dubious feature.
Here is an example of this added complexity:
```scala
#include commonClassesWithImplicitDependencies

object ModuleScope {
  implicit val moduleImplicitDependency = new Dependency()
  
  def service(dep: Dependency) = wire[Service]
  def serviceManual(dep: Dependency) = new Service
}
val dep = new Dependency()
require(ModuleScope.service(dep).dependency eq dep)
require(ModuleScope.serviceManual(dep).dependency eq ModuleScope.moduleImplicitDependency)
```
You can run this example in your tests, it is successful - macwire favors local params over implicit ones.
As you can see this is counter intuitive.

I would just not take implicit parameters into consideration and let the compiler do its job.

**Comment by adamw** [comment]
True, that is definitely confusing. Not the original intention I'm sure :)

**Comment by backuitist** [comment]
In my experience things that are used implicitly are usually consistently used implicitly.
So if you start with this code:
```scala
class Dependency
class ServiceA(dep: Dependency)
trait Module {
   lazy val dependency: Dependency = wire[Dependency]
}
```
It's unlikely that all of a sudden you write this:
```scala
class ServiceB(implicit dep: Dependency)
```
My point is that if every dependency were to be used implicitly then it wouldn't be annoying or disturbing to mark it as implicit:
```scala
class Dep
class OtherDep
class ServiceA(dep: Dep)(implicit other: OtherDep)
class ServiceB(dep: Dep)(implicit other: OtherDep)
trait DepModule {
   lazy val dep: Dep = wire[Dep]
   // what's wrong with this?
   implicit lazy val otherDep: OtherDep = wire[OtherDep]
}
```
My other point is, why would you use implicit parameters as an injection mean when you have a powerful wiring facility (macwire).
What's the benefit of having this:
```scala
class ServiceA(dep: Dep)(implicit other: OtherDep)
```
as opposed to:
```scala
class ServiceA(dep: Dep, other: OtherDep)
```
