### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by adamw** [adamw/macwire#73]
This includes the actual release, updating README.md and di-in-scala

**Comment by backuitist** [comment]
Thanks!

**Comment by adamw** [comment]
Released, should be in Maven Central shortly. I'll write a blog next week, if you don't mind I'll mention you of course :) Could you go through the readme to verify everything correct? I changed the sections on "how wiring works" and added a section on module composition

**Comment by backuitist** [comment]
Great! Of course you can mention me in your blog post :) You might also want me to review it?

About the readme update, in "how wiring works":
> * if the parameter is marked as implicit, additionally the usual implicit lookup mechanism is used

After #66 this isn't exactly true. I'd say that implicit parameters aren't managed by macwire. They are simply injected by the compiler as they would without macwire:
```scala
class A
class B
class C(a: A)(implicit b: B)

object Test {
   lazy val a: A = wire[A]
   implicit val b: B = wire[B]
   lazy val c: C = wire[C] // => new C(a)
}
```
and of course
```scala
object Test {
   lazy val a: A = wire[A]
   lazy val b: B = wire[B] // not implicit anymore
   lazy val c: C = wire[C] // => new C(a) => compilation error: no implicit value of type B found
}
```

This should actually be described in the migration section.

Apart from that it's good!

**Comment by backuitist** [comment]
One minor point:
> MacWire tries to find a value which is a subtype of the parameter's type

A more accurate wording would be: MacWire tries to find a value [conforming](http://www.scala-lang.org/files/archive/spec/2.11/03-types.html#conformance) to the parameter's type.

**Comment by backuitist** [comment]
Just thinking, if you want reviews before things get into master you should consider PR ;)

**Comment by adamw** [comment]
Thanks, added the changes (conforming, migration - implicit, how wiring works).
A PR would probably be good here, you are right, but then it's just a README ;)
