### ISSUE TITLE
Play 2.4 example with PlaySlick

### ISSUE THREAD

**Issue by xevix** [adamw/macwire#89]
Hey. Thanks a million for the [Play 2.4 example with Slick](https://github.com/adamw/macwire/tree/master/examples/play24). Since [PlaySlick is recommended](https://www.playframework.com/documentation/2.4.x/PlaySlick) by Play itself I want to use that instead.

I actually got it working with PlaySlick by modifying `DatabaseModule` to create a `DatabaseConfig` rather than a `db` directly. My DAO then has a dependency on a `DatabaseConfig` which it uses to pull the `db` that it will end up using. Among other things, this allows me to not marry myself to H2, instead importing the appropriate driver from config.

```scala
// DaoModule.scala
trait DaoModule {
  def dbConfig: DatabaseConfig[JdbcProfile]

  lazy val myDao = wire[MyDao]
}

// DatabaseModule.scala
trait DatabaseModule extends DBComponents with HikariCPComponents with SlickComponents {
  def dbApi: DBApi
  // NOTE: manual instantiation
  lazy val dbConfig = api.dbConfig[JdbcProfile](DbName("default"))
}

// MyDao.scala
trait MyDaoLike {
  def all: Future[Seq[MyModel]]
}

class MyDao(dbConfig: DatabaseConfig[JdbcProfile]) extends MyDaoLike {
  import dbConfig.driver.api._

  val db = dbConfig.db
  val myModels = TableQuery[MyModelTable]

  def all: Future[Seq[MyModel]] = db.run(myModels.result)
}
```

My questions are:
* Does this seem sensical?
* Is there a way to avoid the manual instantiation of the `dbConfig` as shown above, instead using MacWire?
* Should the Play 2.4 example use PlaySlick instead, or perhaps have it be a slight variation on this for demonstration purposes? (I'd be happy to make the changes)

Sorry for the long post, and thanks!

**Comment by adamw** [comment]
This definitely makes sense. One thing to note when using Macwire, is that it's meant as a helper library to save time & code on "boring" instantiation code, not a total replacement for new object creation.

So here creating a `DatabaseConfig` instance "by hand" definitely makes sense - especially that it is a result of a method call, not creating a new object via `new` (or so it seems from your example).

If playslick is the recommended way to use slick in play (it seems so :) ), then for sure changing the example would be great. If you'd be willing to create a PR, that would be great!

**Comment by xevix** [comment]
Hah, yes good point. I guess I was looking for an alternative to the method call that used `new` and therefore would use Macwire, but no need to fix what's not broken.

Great, I'll have a stab at it over the holidays. One other doubt is whether I need `def dbApi: DBApi` anymore, but I'll have a look at that later.
