### ISSUE TITLE
Factories example with two Double args in README does not compile

### ISSUE THREAD

**Issue by mbedward** [adamw/macwire#91]
With Scala 2.11.7, macwire 2.2.2, Scala-IDE, this line from the Factories example:
`def taxCalculator(taxBase: Double, taxFreeAmount: Double) = wire[TaxCalculator]`
gives the error "Found multiple values of type [Double]"

Is tagging required to make this work ?

**Comment by adamw** [comment]
Ah yes, that's an old example from the times when we also did by-name matching on method parameters. But this was more confusing then helpful, so now tagging is the "way to go" (or value classes, of course).

Thanks for spotting that!
