### ISSUE TITLE
Should scalatest be in test scope in dependencies?

### ISSUE THREAD

**Issue by DeaconDesperado** [adamw/macwire#98]
See here:
https://github.com/adamw/macwire/blob/master/project/Build.scala#L49

I noticed this when packaging a macwired project with sbt-assembly.  Since the dependency isn't marked as test ivy scope, assembly tries to include into the uber jar it generates.

Is there a reason scalatest is necessary at compile time?  Thanks!

**Comment by adamw** [comment]
Of course not! I think it must have creeped inside during a refactoring. Anyway, 2.2.3 is released, please check if this solves your problem

**Comment by DeaconDesperado** [comment]
Looks good!
